### PR TITLE
Change KML polygon conversion to handle triangular mesh faces

### LINKED ISSUE #463: KML - meshes with triangular faces fail.
Hi @rolyhudson 
I did some test with a different type of geometries and this is not clear for me what are requirements. 
I tested on some model and I got this error for this shape. I would appreciate your advice. I attached my file. 

image

[kmlTest_geometryQuestion.zip](https://github.com/BHoM/XML_Toolkit/files/4632700/kmlTest_geometryQuestion.zip)

### PR DESCRIPTION
**Pull request by rolyhudson**
### Issues addressed by this PR

 Closes #463 
 Conversion from BHoM Mesh to KML Polygon list now handles quad and triangular mesh faces.

 ### Test files
[MeshFaceTests.zip](https://github.com/BHoM/XML_Toolkit/files/4632945/MeshFaceTests.zip)

### CODE REVIEW

File: XML_Adapter/Convert/KML/Mesh.cs [hunk 1]
```diff
@@ -42,9 +42,9 @@ public static List<KML.Polygon> ToKML(this BHG.Mesh mesh, GeoReference geoRefere
                     mesh.Vertices[face.A].DeepClone(),
                     mesh.Vertices[face.B].DeepClone(),
                     mesh.Vertices[face.C].DeepClone(),
-                    mesh.Vertices[face.D].DeepClone(),
                     mesh.Vertices[face.A].DeepClone()
                 };
+                if (face.D > -1) points.Insert(3, mesh.Vertices[face.D].DeepClone());
```
Comment (FraserGreenroyd) [inline XML_Adapter/Convert/KML/Mesh.cs:47]: For consistency within the toolkit, can we re-format this if statement to:
```
if(face.D > -1)
    points.Insert(3, mesh.Vertices[face.D].DeepClone());
```

And also add a blank line above and after the `if` statement to separate it from the other parts of the code.
